### ISSUE TITLE
ip倒是解析成功了，但是py报错，大佬帮忙看看这是什么意思？

### ISSUE THREAD

**Issue by xixihucxixi** [ZhiXuanWang/cf-speed-dns#26]
Traceback (most recent call last):
  File "dnscf.py", line 101, in <module>
    main()
  File "dnscf.py", line 95, in main
    dns = update_dns_record(dns_records[index], CF_DNS_NAME, ip_address)
IndexError: list index out of range
Error: Process completed with exit code 1.

**Comment by JustinHuber** [comment]
dns_records只有一个，数组越界了，我也没搞明白作者在CF上设置一个最优IP有啥用，我自己改了下dns_records[0]

**Comment by iambonboncat** [comment]
> dns_records只有一个，数组越界了，我也没搞明白作者在CF上设置一个最优IP有啥用，我自己改了下dns_records[0]

返回的ip应该是两个，但cf_dns_name的值只能填一个。

**Comment by iambonboncat** [comment]
> dns_records只有一个，数组越界了，我也没搞明白作者在CF上设置一个最优IP有啥用，我自己改了下dns_records[0]

用这个代码就不报错了，挺好的。

**Comment by iambonboncat** [comment]
> 返回的ip应该是两个，但cf_dns_name的值只能填一个。

返回的ip应该是两个，但cf_dns_name的值只能填一个。所以能跟新第一个记录，第二个就会报错，另外，代码里面好像是不会新增记录的，需要现在自己在cf上新增一个记录，它才会自动修改。
