### ISSUE TITLE
部署到CF以后，就不懂咋搞了……

### ISSUE THREAD

**Issue by iambonboncat** [ZhiXuanWang/cf-speed-dns#30]
Run python dnscf.py
cf_dns_change success: ---- Time: 2024-10-12 01:21:09 ---- ip：173.245.49.17
Traceback (most recent call last):
  File "dnscf.py", line 101, in <module>
    main()
  File "dnscf.py", line 95, in main
    dns = update_dns_record(dns_records[index], CF_DNS_NAME, ip_address)
IndexError: list index out of range
Error: Process completed with exit code 1.
是不是因为 response = requests.get('https://ip.164746.xyz/ipTop.html', timeout=timeout)获取的是两个ip
而CF_DNS_NAME（dns.xxxxxxx.com）只能填一个dns记录造成的？

**Comment by iambonboncat** [comment]
貌似是因为获取的ip地址是两个，但cf_dns_name里面只能填一个域名，导致错误发生。另外，代码里面貌似不能新增记录，只会修改记录的ip，需要先在cf上面手动增加一个记录，才可以。
